### ISSUE TITLE
InitialConditions object?

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/roms-tools#10]
A single `Grid` object could be used with a number of different choices of initial conditions (both in time and using different reanalysis datasets), but one choice of initial conditions can only be associated with one `Grid` object.

Perhaps this implies we should make some kind of `InitialConditions` object, which upon creation is fed an existing `Grid` object?

**Comment by NoraLoose** [comment]
This is exactly what I ended up doing. In addition to the `Grid` object, the `InitialConditions` object also is fed the `VerticalCoordinate` object (which essentially holds information about the vertical grid). I think we can close this issue.
