### ISSUE TITLE
Update topography product

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/roms-tools#11]
UCLA-roms setup_tools ships with some netcdf files included (e.g. for the bottom topography and for the tides). But these files were orginally downloaded from external data sources, which have since released newer versions.

I'm not sure how much this particularly matters, but it's worth remembering.

**Comment by NoraLoose** [comment]
I am adding another related TO DO here, see also discussion in #9:
* Need to upload more topography files to https://github.com/CWorthy-ocean/roms-tools-data; currently we only have one file, namely `etopo5.nc`

**Comment by NoraLoose** [comment]
I'm making this issue more specific and renaming it from `Versions of external files` to `Update topography product` since we pretty much have the newest version of all other data products.
