### ISSUE TITLE
save with nx,ny very slow

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/roms-tools#110]
I've noticed that saving each partitioned file takes as long as saving the unpartitioned file. Currently I'm splitting a file 9 ways and so a 3.5 minute save already becomes over half an hour, but when we spin up more realistic domains we'll be using several hundred tiles.

**Comment by NoraLoose** [comment]
We should probably change 
https://github.com/CWorthy-ocean/roms-tools/blob/86785790115d7d711976f7b0042e2a33e0c35ed1/roms_tools/setup/grid.py#L549-L552
to 
```
 dataset_list = [self.ds.compute()] 
 output_filenames = [filepath] 
  
 save_datasets(dataset_list, output_filenames, nx=nx, ny=ny) 
```
i.e., triggering computation before partitioning the file within `save_datasets`.
