### ISSUE TITLE
Pytest Addoption not found

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#126]
In `conftest.py` we have defined

https://github.com/CWorthy-ocean/roms-tools/blob/8f0faac33dc62e72d37cd9e9bc88a8ea4d951004/roms_tools/tests/test_setup/conftest.py#L14-L23

However when I run
```
pytest --use_dask
```
from the top level directory, I get
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --use_dask
  inifile: /global/u2/n/nloose/roms-tools/pyproject.toml
  rootdir: /global/u2/n/nloose/roms-tools
```

The problem does not resolve if
* I move `conftest.py` from `roms_tools/tests/test_setup/` to `roms_tools/tests/`; and
* I add the following lines to the `pyproject.toml`:
```
[pytest]
testpaths = ["roms_tools/tests"]
```

**Comment by TomNicholas** [comment]
Isn't `conftest.py` supposed to be in the root of the entire repo?

**Comment by NoraLoose** [comment]
> Isn't conftest.py supposed to be in the root of the entire repo?

Apparently yes. Your suggestion (#130) solved the issue.
