### ISSUE TITLE
Tests are failing due to ModuleNotFoundError

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#15]
see https://github.com/CWorthy-ocean/roms-tools/actions/runs/8972322248/job/24640316780

The error is 
`ModuleNotFoundError: No module named 'scipy'`

even though `scipy` is now part of https://github.com/CWorthy-ocean/roms-tools/blob/main/ci/environment.yml

@TomNicholas any idea what is going wrong?

**Comment by TomNicholas** [comment]
I have no idea 😕 Does it run locally with an env set up from the same yml file?

**Comment by NoraLoose** [comment]
Locally, I do
```
conda env create -f ci/environment.yml
conda activate romstools-test
```
and then
```
pytest
```
which **successfully** runs the four tests in https://github.com/CWorthy-ocean/roms-tools/blob/main/roms_tools/tests/test_setup.py.

So the `ci/environment.yml` itself seems to be okay.

**Comment by NoraLoose** [comment]
Do we maybe have to add scipy to [`pyproject.toml`](https://github.com/CWorthy-ocean/roms-tools/blob/main/pyproject.toml)?
