### ISSUE TITLE
AMG method fills land with values close to 0 at boundaries

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#150]
The now implemented AMG filling method fills land with values close to 0 at the boundaries:
![Screenshot 2024-09-26 at 9 37 25 AM](https://github.com/user-attachments/assets/f6a83183-181c-4511-bd62-50e915fac869)
For variables like alkalinity, which normally has values order O(2000), this could lead to problems if these close-to-zero values are then used for regridding. (This can happen if the raw data domain is not much bigger than the ROMS domain to be interpolated.)

Question for @sdbachman: What is the best fix for this?

Should we apply the AMG fill method to the field of anomalies instead? So take the following steps:
* `anomaly_field = field - mean` where `mean= field.mean(skipna=True)` 
* AMG lateral fill on `anomaly_field` resulting in `filled`
* `filled = filled + mean`

**Comment by sdbachman** [comment]
In the above example what are you doing to fill in the boundaries and land for the initial guess?   I would assume that if you did an initial fill with `mean(field)` the infilling would remain close to the mean, instead of tapering to zero(?)

**Comment by NoraLoose** [comment]
We are doing this:
https://github.com/CWorthy-ocean/roms-tools/blob/10c0f6dc6e21a87f8cda9cc6acbb5c32e6766bc2/roms_tools/setup/fill.py#L70-L74

Changing to `x0 = xr.where(self.mask, var, np.nanmean(var))` leads to the same result.

**Comment by NoraLoose** [comment]
We are computing the mean of the field already (for `x0`), so it shouldn't slow down things if we instead follow my suggestion above:

> anomaly_field = field - mean where mean= field.mean(skipna=True)
> AMG lateral fill on anomaly_field resulting in filled
> filled = filled + mean

with 
```
 b = xr.where(self.mask, var, 0) 
 x0 = xr.where(self.mask, var, 0) 
```

Thoughts?

**Comment by NoraLoose** [comment]
With this little fix (applying the AMG fill to the anomaly field), I get the following result:
![Screenshot 2024-09-26 at 10 13 02 AM](https://github.com/user-attachments/assets/7397aa5b-6c6b-4dec-8e90-d261c89b707d)

**Comment by sdbachman** [comment]
Seems like a great idea!
