### ISSUE TITLE
Limitations for very large domain sizes

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#22]
For very large specified domain sizes
* our grid generation is probably not very reliable
* the grid plotting function `grid.plot()` struggles

Some examples are found below.

# `size_x = size_y = 10000 km`
```
grid = Grid(nx=500, ny=500, size_x=10000, size_y=10000, center_lon=-21, center_lat=0, rot=20)
```
### Output from `grid.plot()`
<img width="75" alt="Screenshot 2024-05-09 at 10 27 27 AM" src="https://github.com/CWorthy-ocean/roms-tools/assets/23617395/90bee778-3436-40cb-8d7a-2ccba15f9fc0">

### Generated lons and lats
<img width="400" alt="Screenshot 2024-05-09 at 10 32 18 AM" src="https://github.com/CWorthy-ocean/roms-tools/assets/23617395/279e69d6-76f0-432e-a02a-670e1e8d1023">
<img width="400" alt="Screenshot 2024-05-09 at 10 32 23 AM" src="https://github.com/CWorthy-ocean/roms-tools/assets/23617395/fd16e30d-a00c-4b0a-95cd-9f995387c552">

# `size_x = size_y = 20000 km`
```
grid = Grid(nx=500, ny=500, size_x=20000, size_y=20000, center_lon=-21, center_lat=0, rot=20)
```
### Output from `grid.plot()`
<img width="795" alt="Screenshot 2024-05-09 at 10 27 43 AM" src="https://github.com/CWorthy-ocean/roms-tools/assets/23617395/079c9e55-2e30-4862-a265-ba50d118c3d1">

### Generated lons and lats
<img width="400" alt="Screenshot 2024-05-09 at 10 34 29 AM" src="https://github.com/CWorthy-ocean/roms-tools/assets/23617395/d3420f83-f200-4ac4-8124-3857c56a6ae1">
<img width="400" alt="Screenshot 2024-05-09 at 10 34 37 AM" src="https://github.com/CWorthy-ocean/roms-tools/assets/23617395/8974ce9e-cd21-4738-bb8c-28aeebb3bb13">

Since the generated longitudes and latitudes still look more or less reasonable for domains up to 20 000 km (see above), I chose this number as a treshold in #21. But we may need to adjust this threshold in the future. (I don't know of a good strategy of how to come up with a good threshold.) Note that even for domain sizes smaller than that, the `grid.plot()` function struggles.

**Comment by NoraLoose** [comment]
For reference: The circumference of Earth is approximately 40 000km.

**Comment by sdbachman** [comment]
I think we can make a reasonable threshold by considering a few factors:

1) UCLA-ROMS has been benchmarked to be most performant for grid sizes ~1000 x 1000 (not necessarily square) and ~400 cores.
2) UCLA-ROMS is a regional model and does not have any mesoscale parameterization such as GM or Redi, so we would not want to use it at lower-than-eddy-permitting resolution (< 25 km).
3) UCLA-ROMS can't do sea ice, so we would never want a domain so large that it includes very high latitudes.
4) It is unlikely that we would ever want to run a simulation with forcing that is much coarser than modern reanalysis datasets, of which many are available at ~1/4 degree resolution.

Altogether I think this suggests that 20,000 km is a pretty reasonable threshold!   We can consider different functions or strategies for generating the grid.plot().
