### ISSUE TITLE
Distributing TPXO tidal atlas

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#24]
To create the tidal forcing (step 3 in #1), we need to interpolate data from the TPXO tidal atlas. The file size is 1.2 GB. Should we upload it to https://github.com/CWorthy-ocean/roms-tools-data and fetch it with pooch from there? What do you recommend @TomNicholas?

**Comment by NoraLoose** [comment]
Okay, sounds good. Do you mind uploading the file to https://github.com/CWorthy-ocean/roms-tools-data, @sdbachman?

**Comment by NoraLoose** [comment]
upon attempting upload @sdbachman is encountering the following error:
`remote: error: File tides/tpxo9.v2a.nc is 1205.76 MB; this exceeds GitHub's file size limit of 100.00 MB`

**Comment by TomNicholas** [comment]
Okay well that's a no-go then. I guess we'll have to just stick it in an AWS bucket then?

**Comment by NoraLoose** [comment]
Do we have the resources on AWS? If yes, could you help with setting this up @TomNicholas?

**Comment by TomNicholas** [comment]
We do - I have the credentials for the CWorthy AWS account. This is worth a call to show you how to do it though.

**Comment by NoraLoose** [comment]
Sounds good, thanks! Pinged you on slack.

**Comment by NoraLoose** [comment]
I'm closing this because we require the user to download the TPXO data themselves (as instructed [here](https://roms-tools.readthedocs.io/en/latest/datasets.html)), among other things, for legal reasons. In the future, we should think about a cloud-based solution. I will open a separate issue on that.
