### ISSUE TITLE
Domains which cross Greenwich meridian

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/roms-tools#3]
@sdbachman and I are unsure if ROMS can handle grids which cross the Greenwich Meridian (or the international dateline). For the moment I've [forbidden the user](https://github.com/CWorthy-ocean/roms-tools/blob/36d0b1d5d96f408c42e34ef1cdc33f8713e93f4a/roms_tools/setup/grid.py#L216) from creating any grid which crosses the Greenwich Meridian, but it would be nice to support this.

**Comment by NoraLoose** [comment]
> @sdbachman and I are unsure if ROMS can handle grids which cross the Greenwich Meridian (or the international dateline).

Maybe @ubbu36 knows the answer to this question? If ROMS can handle it, I will modify [grid.py](https://github.com/CWorthy-ocean/roms-tools/blob/main/roms_tools/setup/grid.py) to support domains that cross the Greenwich Meridian.

**Comment by ubbu36** [comment]
@NoraLoose The setup tools for atmospheric boundary conditions currently do not support crossing the 0th meridian. I'm not sure if the other setup tools support it or not, we should check. But this should be an easy fix.

**Comment by NoraLoose** [comment]
Our python tools will enable such domains. I'm closing this issue.
