### ISSUE TITLE
Format of atmospheric forcing files

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#31]
The matlab scripts produce atmospheric forcing files sorted by months, e.g.,
```
CT0_frc.201901.nc
CT0_frc.201902.nc
CT0_frc.201903.nc
...
```
Does ROMS need the atmospheric forcing files in this format? Or could we also write the forcing data into a zarr store? Probably not since the model only knows how to read netcdf files?

**Comment by sdbachman** [comment]
Correct, ROMS only knows how to read NetCDF.   The files don't necessarily have to be sorted by months, though -- we could make new files as frequently or as infrequently as we want.

**Comment by NoraLoose** [comment]
ok, thanks @sdbachman!
