### ISSUE TITLE
Step 8a and 9a: fix patchwork solution to get observed BGC input for IC and BC

### ISSUE THREAD

**Issue by ubbu36** [CWorthy-ocean/roms-tools#44]
The 8a and 9a steps need the following:

1. the patchwork of model and observed data should be streamlined so that missing data ['Lig','DIC_ALT_CO2','ALK_ALT_CO2','DOCr','spP','diatP','diazP'] are initialized from MOM rather than from 0.

2. The lowercase/upper case difference between BEC and MARBL should be fixed

3. BGC boundary conditions should be in a separate file and not added on to the physics boundary conditions so it's easier to partition afterwards, and faster to produce.

**Comment by NoraLoose** [comment]
> The lowercase/upper case difference between BEC and MARBL should be fixed

@ubbu36 what is the lowercase/upper case difference?

**Comment by dafyddstephenson** [comment]
@NoraLoose BEC ships with (I think 26) tracers, all but one of which are also present in MARBL, but with slightly different names, typically down to a case difference. Here's a dictionary I've been using to keep track
```
BEC_to_MARBL_tracers={
    'PO4':'PO4',        
    'NO3':'NO3',        
    'SiO3':'SiO3',      
    'NH4':'NH4',        
    'Fe':'Fe',         
    'O2':'O2',         
    'DIC':'DIC',       
    'Alk':'ALK',        
    'DOC':'DOC',        
    'DON':'DON',        
    'DOP':'DOP',        
    'DOPR':'DOPr',      
    'DONR':'DONr',      
    'ZOOC':'zooC',      
    'SPCHL':'spChl',    
    'SPC':'spC',        
    'SPFE':'spFe',      
    'SPCACO3':'spCaCO3',
    'DIATCHL':'diatChl',
    'DIATC':'diatC',    
    'DIATFE':'diatFe', 
    'DIATSI':'diatSi', 
    'DIAZCHL':'diazChl'
    'DIAZC':'diazC',    
    'DIAZFE':'diazFe',  
    'DOFE':None}  
```

... _However_ , a conversation between Jeroen and I about removing case sensitivity in ROMS last week illuminated that, while MARBL's tracer names are fixed, BEC's are not, and we can just change `tracers.opt` in ROMS to make them align with MARBL's naming conventions. I think with this in mind we should create things in roms-tools as if for MARBL and then rely on the user changing the names in `tracers.opt` if they wish to run with BEC.

**Comment by NoraLoose** [comment]
Okay, thanks! The tracer names in `ROMS-Tools` match the names that MARBL expect (the dictionary values above).

As for the other comments:

> the patchwork of model and observed data should be streamlined so that missing data ['Lig','DIC_ALT_CO2','ALK_ALT_CO2','DOCr','spP','diatP','diazP'] are initialized from MOM rather than from 0.

`ROMS-Tools` does not do any patchwork (as the matlab scripts) but rather assumes that you feed it a harmonized dataset.

> BGC boundary conditions should be in a separate file and not added on to the physics boundary conditions so it's easier to partition afterwards, and faster to produce.

Yes, I'm writing out separate files for physical vs. BGC boundary conditions.

I think we can close this issue.
