### ISSUE TITLE
Step 6: make monthly files rather than one long file

### ISSUE THREAD

**Issue by ubbu36** [CWorthy-ocean/roms-tools#45]
Step 6: This step should produce monthly files that are much easier to handle in partitioning similarly to the atmospheric forcing files.

With all the BGC tracers,the netcdf files become massive to handle and for say a year worth of boundary forcing, it doesn't make sense to have a single netcdf file to partition

**Comment by NoraLoose** [comment]
Thanks for this suggestion! I have written `ROMS-Tools` in a way that it writes monthly NetCDF files also for the boundary forcing (see #62). I'm closing this issue.
