### ISSUE TITLE
Pytest fails in multi-threaded context

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#61]
When I run 
```
pytest test_atmospheric_forcing.py
```
on perlmutter I run into the following error:
```
Thread 0x00007f8ff1163700 (most recent call first):
  File "/global/homes/n/nloose/.conda/envs/romstools/lib/python3.12/concurrent/futures/thread.py", line 89 in _worker
  File "/global/homes/n/nloose/.conda/envs/romstools/lib/python3.12/threading.py", line 1010 in run
  File "/global/homes/n/nloose/.conda/envs/romstools/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/global/homes/n/nloose/.conda/envs/romstools/lib/python3.12/threading.py", line 1030 in _bootstrap
```

In contrast, if I execute all tests within `test_atmospheric_forcing.py` sequentially, i.e.,
```
pytest test_atmospheric_forcing.py::test_successful_initialization_with_regional_data
pytest test_atmospheric_forcing.py::test_no_longitude_intersection_initialization_with_regional_data
...
```
the entire test suite runs successfully.

What's going on?

**Comment by NoraLoose** [comment]
This happens when running the test suite on perlmutter. Need to be fixed before the C-Star alpha release. Any ideas for what's going on @TomNicholas?

**Comment by TomNicholas** [comment]
I don't know why that happens, but using [pytest-xdist](https://github.com/pytest-dev/pytest-xdist) might be one way to avoid it?

**Comment by NoraLoose** [comment]
With `pytest-xdist` there are no errors anymore on Perlmutter, but the pytest suite simply stops after 33% of the tests are executed.

**Comment by NoraLoose** [comment]
Update on this issue:
* After merging #121 and #128, which enabled running the tests without dask, this was no longer an issue (unless you did `pytest --use_dask`)
* After merging #140, which got rid of numba, we can now also run `pytest --use_dask` on perlmutter without issues

To summarize, this was an issue related to the combination of `dask` and `numba` on perlmutter. Using each of them in isolation worked fine. Now `numba` is not used within `ROMS-Tools` anymore, so this is no longer an issue, and I'm closing it.
