### ISSUE TITLE
Combine `Grid` and `VerticalCoordinate` objects

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#71]
@dafyddstephenson and I just discussed to potentially combine the `Grid` and `VerticalCoordinate` objects into one object. The `.save()` method of the combined object would then write a netcdf file that has the following coordinates:
* lat/lon information at tracer, u- and v-points
* layer and interface depth at tracer, u- and v-points

While ROMS does not need any of these information (except lat information to compute the Coriolis parameter), this will be a useful reference file for the user to make plots etc.

As of now these coordinates are written as part of the initial conditions, boundary forcing files, etc. It would be better to have them all in one place, and maybe not clutter the ROMS input files with (for the model) unnecessary information.

**Comment by dafyddstephenson** [comment]
I would float that we extend this to the boundary variables that aren't directly needed by the model too (`xi_rho_south` etc.), such that the grid file becomes a single reference file from which the user can get _all_ grid-related information for analysis.

**Comment by NoraLoose** [comment]
Closing this because addressed in #81. I still have to remove the coordinates from the initial conditions, boundary forcing, and surface forcing input files, but this issue is tracked in #68.
