### ISSUE TITLE
Land masking?

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/roms-tools#75]
Just raising this issue to record our discussion earlier. Key points:

- MATLAB version masks land in some cases (e.g. for tides) while python doesn't (not strictly a problem)
- Perhaps should have this as an optional behaviour with a parameter allowing the user to specify the mask value?

ROMS behaviour is apparently _not_ to mask land points, but to discard values calculated over land at the end of each time step, which may be a factor to keep in mind

**Comment by NoraLoose** [comment]
@nmolem what fill value do you recommend to set in the ROMS input fields over land? 

I would have suggested NaNs (so the user has an immediate visual if they plot the input field). But after our discussion last week, it seems that NaNs over land may lead to issues because ROMS still computes over land.

**Comment by NoraLoose** [comment]
Okay, sounds good. Thanks for your insights and recommendation @nmolem!

**Comment by NoraLoose** [comment]
@nmolem related to what to do over land. 

Your MATLAB scripts zero out the ocean velocities over land (i.e., in particular they do not keep the inpaint_nans values there). More specifically, the scripts seem to follow these steps:

1. Interpolate velocities to ROMS rho-points with extrapolated inpaint_nans values over land
2. Interpolate velocities from rho-points to u- and v-points resulting in variables `u` and `v`
3. Set `u` and `v` to zero over land: 
```
u = u * umask
v = v * vmask
```
4. Compute barotropic velocities
```
ubar = sum(u*dzu) / sum(dzu)
vbar = sum(v*dzv) / sum(dzv)
```
I'm not sure why step 3 is necessary. Does it help with the problem that the denominators in step 4 can be really small over land?

**Comment by nmolem** [comment]
You're right, step 3 isn't neccesary at all. It's purely cosmetic as u, and v will be multiplied with the umask and vmask during the integration of the model

**Comment by nmolem** [comment]
You are correct, we could, with the caveat of using mask_u and mask_v where appropriate. The only reason to not multiply them by a zero (or setting any other filvalue) would be to allow for the mask to be changed and still be able to use the same forcing and initial fields as I mentioned earlier. Also, as discussed earlier, Roms can't handle NaN's in and input variable.
