### ISSUE TITLE
`BoundaryForcing` issues

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/roms-tools#76]
There is some problem with the output of the boundary forcing step, causing `partit` to return:

```
 ### ERROR: insert_node :: a non-digital character found in index 
                    segment of name 'roms_bry.201201.patched.nc'.
```
The `patched` in the filename above corresponds to several changes I've made to bring the file more in line with that produced by the MATLAB scripts:

1. Rename `xi_rho_south` etc. to `xi_rho` in the dimensions [unsure if needed]
2. rename `time` to `bry_time` [needed, the `bry_time` name is hardcoded in ROMS]
3. drop extra coordinates, e.g. `layer_depth_rho_south` [unsure if needed]
4. Transpose dimensions to e.g. `bry_time`,`s_rho`,`eta_rho`,`xi_rho` [needed by ROMS]

... however, none of these changes have fixed the problem raised by `partit`

**Comment by dafyddstephenson** [comment]
Ok, I've managed to get it to the point where partit produces something and ROMS accepts it. The error from `partit` came from the fact that there are `.`s in the filename, so we should probably avoid using those. Bizarrely, the `.`s in the surface forcing filenames are fine according to `partit` (???)

I have now verified that dimension order is also important to ROMS, so we will need to transpose those.

However ROMS blows up immediately and ncview shows some very weird values on the boundary. Will take a deeper look tomorrow. I think for now doing the 4 steps above and changing the filename pattern should be a good start. I think moving the additional dims/coords into the grid (#71 ) will avoid any ambiguity there as we chatted about

**Comment by NoraLoose** [comment]
Thanks for digging into this! 

> rename time to bry_time [needed, the bry_time name is hardcoded in ROMS]

Do you mean **dimension** name here?

**Comment by dafyddstephenson** [comment]
Good point - I just noticed that `bry_time` exists as a variable here, which is probably fine as `time` isn't a partition-able dimension anyway.

**Comment by NoraLoose** [comment]
It would be nice to have some consistency among the input fields when it comes to the time dimension / variable. I'm suggesting the following:

* surface forcing: dimension `time`, variable `sfc_time`
* initial conditions: dimension `time`, variable `ocean_time`
* boundary forcing: dimension `time`, variable `bry_time`

Do you foresee either `partit` or `ROMS` to dislike this convention?

**Comment by NoraLoose** [comment]
As far as I understand, we can set the variable names for the surface forcing and initial conditions in the ROMS opt files. Correct?

**Comment by dafyddstephenson** [comment]
only the surface forcing - I think having `time` as the dimension is fine as long as there is a variable with the correct name along that dimension. For example, each bgc variable in the surface forcing has its own "time name" to allow them to be e.g. applied with different frequencies. These names can be controlled, but the current convention of e.g. `iron_time` seems intuitive.

**Comment by dafyddstephenson** [comment]
> It would be nice to have some consistency among the input fields when it comes to the time dimension / variable. I'm suggesting the following:
> 
>     * surface forcing: dimension `time`, variable `sfc_time`
> 
>     * initial conditions: dimension `time`, variable `ocean_time`
> 
>     * boundary forcing: dimension `time`, variable `bry_time`
> 
> 
> Do you foresee either `partit` or `ROMS` to dislike this convention?

I think this is fine apart from `sfc_time` (see above comment). It would work, but seems restrictive. I think the BGC datasets we'll eventually be working with post-CESM will have different frequencies for different variables.

**Comment by NoraLoose** [comment]
We could have `sfc_time` as the default name (if all variables in the same netcdf file have the frequency). This will often be the case for the physical forcing variables. If variables in the same netcdf file have different frequencies, we can default to each giving them their own time variable: `iron_time`, `pco2_time`, etc.

What do you think?

**Comment by dafyddstephenson** [comment]
... I think if we deviate from these conventions we should discuss issuing a PR to change the ROMS defaults with CESR. I (personally!) think we should try and stick to "roms-tools defaults align with ROMS defaults". If ROMS defaults don't make sense for some reason it is totally reasonable to find out why and suggest changing them.

**Comment by NoraLoose** [comment]
From a ROMS-Tools perspective, there is value in having distinct names for the time dimension and time variable name. In this case, we would be able to assign a coordinate to the `time` dimension with the absolute time, e.g.,
```
array(['2012-01-15T00:00:00.000000000', '2012-01-15T01:00:00.000000000',
       '2012-01-15T02:00:00.000000000', ..., '2012-03-14T21:00:00.000000000',
       '2012-03-14T22:00:00.000000000', '2012-03-14T23:00:00.000000000'],
      dtype='datetime64[ns]')
```
where as the time variable `bry_time` will have a more opaque format to the user (time since reference date)
```
array([4397.      , 4397.041667, 4397.083333, ..., 4456.875   , 4456.916667,
       4456.958333])
```
If the dimension and variable name coincide, we have to overwrite the more readable version (the first one) with the more opaque version (the second one). If they don't coincide, they could live next to each other. My suggestion has both advantages and disadvantages:
* Disadvantage: If the user forgets to change the time name from `time` to `sfc_time` or `bry_time`, ROMS will read the absolute time and throw an error.
* Advantage: More transparency and human-readability

**Comment by NoraLoose** [comment]
Alternatively, we could just introduce a separate variable like `absolute_time` that holds the more readable format, but does not interfere with ROMS.

**Comment by NoraLoose** [comment]
> ocean_time for initial condition variables (hardcoded in [basic_output.F](https://github.com/CESR-lab/ucla-roms/blob/main/src/basic_output.F#L149-L155) although according to [get_init.F](https://github.com/CESR-lab/ucla-roms/blob/main/src/get_init.F#L167-L177) they can also be roms_time or scrum_time)

`scrum_time`???

**Comment by dafyddstephenson** [comment]
I think I'm a bit lost. We'd have a dimension `time`, a co-ordinate `time` with human-readable values, and variables `bry_time`, `ocean_time` etc. defined on the `time` dimension? The only place where there would be a naming clash in the defaults in this case is for the physics surface forcing? I think we could make the case here to change the default name in ROMS for consistency with the other forcing types.

**Comment by NoraLoose** [comment]
> I think I'm a bit lost. We'd have a dimension time, a co-ordinate time with human-readable values, and variables bry_time, ocean_time etc. defined on the time dimension?

Exactly. I think only xarray makes a distinction between coordinates and variables, though. So for ROMS the coordinate time might look like a variable. Therefor the potential clash for the physical surface forcing.

I agree that it would be nicest to change the default name in ROMS for the physical surface forcing. Until then, I will just keep the human-readable variable separate as `abs_time` for surface forcing, initial conditions, and boundary forcing.

**Comment by dafyddstephenson** [comment]
sounds good!

**Comment by NoraLoose** [comment]
> However ROMS blows up immediately and ncview shows some very weird values on the boundary. Will take a deeper look tomorrow.

Maybe it has to do with the fact that ROMS-Tools is interpolating in the vertical rather than the horizontal, see the discussion in
https://github.com/CWorthy-ocean/roms-tools/issues/70
