### ISSUE TITLE
What discrete choices get made during setup?

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/roms-tools#9]
The matlab tools have 6 separate steps, but that doesn't mean that the ROMS user actually needs to make a new choice at each of those steps. For example when you create the grid (step 1) you choose the location on the earth of the domain, but when you make the topography (step 2) you don't make a new choice, the topography just has to be for the region you chose in step 1.

We should try to fuse together different steps in this workflow so that the user is only required to do anything when there is an actual new choice to be made.

How many discrete choices are there? At least:
1) Choose the resolution, size, and location of the domain,
2) Choose the time resolution you want to run with (needed for tides + forcing data?),
3) Choose which data sources you want to use for the initial/boundary/forcing data

Are there any others? What about choice of processor decomposition?

@ubbu36

**Comment by NoraLoose** [comment]
> For example when you create the grid (step 1) you choose the location on the earth of the domain, but when you make the topography (step 2) you don't make a new choice, the topography just has to be for the region you chose in step 1.

There is actually a new decision involved when adding the topography, namely which data source to use. The matlab code allows 8 different choices, see https://github.com/CWorthy-ocean/C-Star/blob/6dfebe86eba059f3732764fa8ff99d9cd412290a/setup_tools/setup_r2r_phys%2Bbgc/2.Make_topo/topo.m#L57-L80.

 @sdbachman @TomNicholas  Do we want to give the user the option to choose from different data sources for the topography? Probably yes... If so, we need to 
* upload more files to https://github.com/CWorthy-ocean/roms-tools-data. (Currently, we only have one, namely `etopo5.nc`.) Who can provide these files?
* modify the grid object to take one more parameter, something like
```
grid = Grid(
    nx=100,          # number of points in the x-direction (not including 2 boundary cells on either end)
    ny=100,          # number of points in the y-direction (not including 2 boundary cells on either end)
    size_x=1800,     # size of the domain in the x-direction (in km)
    size_y=2400,     # size of the domain in the y-direction (in km)
    center_lon=-21,  # longitude of the center of the domain
    center_lat=61,   # latitude of the center of the domain
    rot=20,          # rotation of the grid's x-direction from lines of constant longitude, with positive values being a counter-clockwise rotation
    topography_source = "etopo5" 
)
```

**Comment by TomNicholas** [comment]
I feel like we discussed this a while ago and thought that in practice topography is unlikely to be something that anyone really cares about changing...

**Comment by TomNicholas** [comment]
That said an optional topography_source kwarg seems nice and neat, and it can just default to etopo5.

**Comment by NoraLoose** [comment]
I think we can close this issue. I have created the different objects / classes with exactly this question in mind, which led to designing 6 distinct classes:
* `Grid`
* `VerticalCoordinate`
* `TidalForcing`
* `AtmosphericForcing`
* `InitialConditions`
* `BoundaryForcing`
