### ISSUE TITLE
`Mismatch in 'Cs_r' values` in IC file

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/roms-tools#92]
This isn't going to be a very useful issue as I can't pin this down very well - sorry! 
ROMS is throwing
` ### ERROR: Mismatch in 'Cs_r' values in file 'INPUT/PYTHON/PARTED/roms_ini.0.nc'.`
And it seems that `partit` isn't doing a proper job here. If I load the unpartitioned file everything looks fine, but opening the partitioned one `Cs_r` seems to be full of 0s. `ncdump -v Cs_r` consistently shows an array of 0s. `ncview` also shows 0s.

xarray is being worryingly inconsistent, sometimes showing that the partitioned python-created file has the correct values, sometimes showing it having 0s:

```
In [11]: xr.open_dataset('PYTHON/PARTED/roms_ini.8.nc').Cs_r.values
Out[11]: 
array([-9.91966903e-01, -9.75310326e-01, -9.57903922e-01, -9.39797223e-01,
       -9.21044052e-01, -9.01701748e-01, -8.81830335e-01, -8.61491978e-01,
       -8.40749860e-01, -8.19667757e-01, -7.98309207e-01, -7.76737094e-01,
       -7.55012929e-01, -7.33196437e-01, -7.11345196e-01, -6.89514160e-01,
       -6.67755604e-01, -6.46118581e-01, -6.24649167e-01, -6.03389859e-01,
       -5.82379997e-01, -5.61655402e-01, -5.41248500e-01, -5.21188438e-01,
       -5.01500964e-01, -4.82208848e-01, -4.63331670e-01, -4.44886118e-01,
       -4.26886171e-01, -4.09343123e-01, -3.92265856e-01, -3.75660986e-01,
       -3.59532982e-01, -3.43884379e-01, -3.28715861e-01, -3.14026594e-01,
       -2.99814165e-01, -2.86074877e-01, -2.72803813e-01, -2.59995013e-01,
       -2.47641608e-01, -2.35735863e-01, -2.24269405e-01, -2.13233232e-01,
       -2.02617854e-01, -1.92413345e-01, -1.82609484e-01, -1.73195779e-01,
       -1.64161548e-01, -1.55495971e-01, -1.47188202e-01, -1.39227331e-01,
       -1.31602496e-01, -1.24302894e-01, -1.17317833e-01, -1.10636741e-01,
       -1.04249209e-01, -9.81450155e-02, -9.23141390e-02, -8.67467746e-02,
       -8.14333707e-02, -7.63645992e-02, -7.15314075e-02, -6.69250041e-02,
       -6.25368580e-02, -5.83587363e-02, -5.43826595e-02, -5.06009422e-02,
       -4.70061824e-02, -4.35912535e-02, -4.03493047e-02, -3.72737721e-02,
       -3.43583524e-02, -3.15970331e-02, -2.89840512e-02, -2.65139174e-02,
       -2.41813995e-02, -2.19815224e-02, -1.99095625e-02, -1.79610383e-02,
       -1.61317140e-02, -1.44175906e-02, -1.28148990e-02, -1.13201011e-02,
       -9.92987957e-03, -8.64113960e-03, -7.45099736e-03, -6.35678275e-03,
       -5.35603240e-03, -4.44648601e-03, -3.62608512e-03, -2.89296708e-03,
       -2.24546436e-03, -1.68210152e-03, -1.20159215e-03, -8.02837836e-04,
       -4.84925782e-04, -2.47127580e-04, -8.88979121e-05, -9.87376825e-06],
      dtype=float32)
```

vs. (what should be identical)

```
In [13]: [xr.open_dataset(f'PYTHON/PARTED/roms_ini.{i}.nc').Cs_r.values for i in range(9)][-1]
Out[13]: 
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
```

... Sorry I can't be more helpful than to say something is screwy here 😬

**Comment by dafyddstephenson** [comment]
What a horrible gift to give at 4:59 on a Friday. Sorry!

**Comment by dafyddstephenson** [comment]
...There seems to be a bigger problem as I managed to correct the `Cs_r` issue by just copying in the correct values from the MATLAB version (worked with ncks but not xarray 😝) only to find the other variables are also screwy (mostly nans or O(e32)) after running `partit`, causing ROMS to blow up immediately.

**Comment by dafyddstephenson** [comment]
related: #93 #95

**Comment by dafyddstephenson** [comment]
... This issue also occurs when I `save` the `Grid` I create using `from_file` with the MATLAB-generated grid and give it to ROMS instead of the MATLAB version

**Comment by NoraLoose** [comment]
This is very strange. Can you point me to your partitioned files?

**Comment by dafyddstephenson** [comment]
https://drive.google.com/drive/folders/105yUTP7lNw1HAWAW17-kz89jX2Adtytu?usp=sharing

But also you can get there by making a Grid instance from the [`roms_marbl_example` grid file](https://github.com/CWorthy-ocean/input_datasets_roms_marbl_example/blob/main/roms_grd.nc), then following the other steps and running `partit 3 3 roms_tools_output_file.nc` (`partit` will be on your path if you've installed ROMS) on anything produced by roms-tools.

**Comment by NoraLoose** [comment]
@dafyddstephenson can we close this?
