### ISSUE TITLE
`time` does not survive `partit` for BGC surface forcing

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/roms-tools#93]
in the unpartitioned file:
` time = 4383 ;`
in the partitioned file on every tile:
`time = 0 ;`

Interestingly this is not a problem in the physics file.

**Comment by dafyddstephenson** [comment]
... again, a quick check shows this isn't just limited to `time` - every variable gets messed up. (Again not a problem in the physics file)

**Comment by dafyddstephenson** [comment]
Related : #92 #95

**Comment by NoraLoose** [comment]
Maybe we should prioritize rewriting `partit` with `xarray` since `partit` screws up all ROMS-Tools generated input fields. cc @TomNicholas

**Comment by NoraLoose** [comment]
@dafyddstephenson can we close this?
